FROM jenkins/jenkins:lts

USER root

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
      ca-certificates \
      curl \
      gnupg \
      lsb-release

# Install Docker CLI (official)
RUN curl -fsSL https://get.docker.com | sh

# Allow jenkins user to run docker
RUN usermod -aG docker jenkins

USER jenkins